CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    QTD_MUSICAS INTEGER NOT NULL,
    DESCRICAO VARCHAR(450),
    AVALIACAO VARCHAR(250),
    PRODUTOR VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    FK_CPF_ARTISTA VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    LETRA VARCHAR(1000),
    DATA_LANCAMENTO DATE NOT NULL,
    COMENTARIO VARCHAR(600),
    FAIXA_ETARIA INTEGER NOT NULL,
    QTD_VISUALIZACOES VARCHAR(15) NOT NULL,
    FK_ID_GENERO INTEGER NOT NULL,
    FK_ID_ALBUM INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_GENERO) REFERENCES GENERO(ID),
    FOREIGN KEY (FK_ID_ALBUM) REFERENCES ALBUM(ID)
);