CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS;
USE BD_CONSULTAS_MEDICAS;

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE INTEGER NOT NULL,
    LAUDO VARCHAR(380) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(50) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    ESPECIALIZACAO VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    FOTO BLOB,
    SALARIO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_CONSULTA DATE,
    FK_CRM_MEDICO VARCHAR(50) NOT NULL,
    FK_CPF_PACIENTE VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);