CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL", "MÉDIO", "SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY (USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(1000) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY (URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(500) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY (RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);

-- Tabela para inserir dados USUARIO

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-10-01", "Thaiene", "Saúde", "Enfermeira", "Técnico de enfermagem", "2008-05-23", "SOLTEIRO", "SP", "MÉDIO", "thaienetessaro@gmail.com", "Ta123", "Thaiene Tessaro");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-10-01", "Giulia", "Ensino", "Professora", "Licenciatura", "2008-12-26", "CASADO", "MG", "SUPERIOR", "giulia@gmail.com", "Gih1313", "Giulia Ribeiro");

INSERT INTO USUARIO (USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, USU_SENHA, USU_NOME)
VALUES ("2025-10-01", "Neto", "Esporte", "Jogador profissional", "Meia Ofenciva", "2008-06-05", "VIÚVO", "RJ", "FUNDAMENTAL", "netox@hotmail.com", "Netox.080912", "Rubens Neto Moscardini");

SELECT * FROM USUARIO;

-- Tabela para inserir dados ENQUETE

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-10-23", "2025-10-01", "O que o passáro é?", "Pássaro", 1);

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-10-23", "2025-10-01", "O que é uma pergunta?", "Filosofando", 3);

INSERT INTO ENQUETE (ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES ("2025-10-23", "2025-10-01", "Eu sou bonita?", "Teste de Autoestima", 2);

SELECT * FROM ENQUETE;

-- Tabela para inserir dados USUARIO_RESPONDE_ENQUETE

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", 1, 1);

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", 3, 2);

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES ("2025-10-01", 2, 3);

SELECT * FROM USUARIO_RESPONDE_ENQUETE;

-- Tabela para inserir dados PERGUNTAS

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("Falando sobre pássaros", 1);

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("Filosofando com Gustavo", 2);

INSERT INTO PERGUNTAS (PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES ("Falando sobre Autoestima", 3);

SELECT * FROM PERGUNTAS;

-- Tabela para inserir dados RESPOSTAS

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("Você é feia", "F", 3);

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("É uma afirmação", "F", 2);

INSERT INTO RESPOSTAS (RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES ("Lógico que é uma ave", "V", 1);

SELECT * FROM RESPOSTAS;
