CREATE DATABASE IF NOT EXISTS BD_GERENCIAR_PROJETOS;
USE BD_GERENCIAR_PROJETOS;

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    FOTO BLOB,
    NUM_CARTEIRA VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(800) NOT NULL,
    QTD INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(800) NOT NULL,
    CATEGORIA VARCHAR(255),
    FK_ID_PROJETO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CPF_FUNCIONARIO VARCHAR(14) NOT NULL,
    FK_ID_TAREFA INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_TAREFA) REFERENCES TAREFA(ID) ON DELETE CASCADE
);