CREATE DATABASE IF NOT EXISTS BD_RESERVAS_AEREAS;
USE BD_RESERVAS_AEREAS;

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_VOO DATE NOT NULL,
    VALOR DOUBLE NOT NULL, 
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(800) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    COMPANIA VARCHAR(255) NOT NULL,
    QTD_PASSAGEIROS INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    PASSAPORTE VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUM INTEGER NOT NULL,
    DESCRICAO VARCHAR(800),
    VALOR DOUBLE NOT NULL,
    FK_ID_VOO INTEGER NOT NULL,
    FK_CPF_PASSAGEIRO VARCHAR(14) NOT NULL,
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE
);