CREATE DATABASE IF NOT EXISTS BD_STREAM_VIDEO;
USE BD_STREAM_VIDEO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE INTEGER,
    DESCRICAO VARCHAR(800)
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TEMPO VARCHAR(15) NOT NULL,
    FK_ID_CATEGORIA INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VISUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERACAO VARCHAR(255),
    FK_ID_VIDEO INTEGER NOT NULL,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES VIDEO(ID) ON DELETE CASCADE
);
