USE BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR; 

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES 
("12335678000101", "Supermercado Gricki", "(19) 99823-4410 ", "grickitambau@email.com", "Gricki Street", "10000", "TambaCity", "SP"),
("27894563000155", "Supermercado do Sol", "(19) 99182-3345", "contato@superdosol.com", "Rua das Flores", "120", "Campinas", "SP"),
("56433219000189", "Supermercado Central", "(19) 98765-1122", "vendas@supercentral.com", "Avenida Brasil", "4500", "Ribeirão Preto", "SP"),
("89745632000102", "Supermercado Tech", "(19) 99664-7788", "suporte@supertech.com", "Rua da Inovação", "300", "Piracicaba", "SP"),
("33428977000144", "Supermercado Sabor", "(19) 99987-5521", "sabor@email.com", "Travessa das Palmeiras", "75", "São Carlos", "SP");

-- Desse jeito foi TBM
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7891234567890", "Arroz 5kg", 5.0, 500, 26.90, "2025-12-25");
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7894561239876", "Feijão Carioca 1kg", 1.0, 300, 8.75, "2025-11-10");
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7896543217890", "Açúcar Refinado 2kg", 2.0, 400, 6.40, "2026-01-15");
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7893216540987", "Óleo de Soja 900ml", 0.9, 250, 7.90, "2025-09-20");
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("7897412589630", "Macarrão Espaguete 500g", 0.5, 600, 5.20, "2026-03-05");


INSERT INTO CONSUIMIDOR (CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES
('41531446817', 'Thaiene Tessaro', '(19)99112-6878', 'thaienetessaro@gmail.com'),
('52987412390', 'Lucas Andrade', '(19)99745-3201', 'lucasandrade@email.com'),
('38421657902', 'Mariana Oliveira', '(19)99658-7742', 'mariana.oli@gmail.com'),
('71894563211', 'João Pedro Santos', '(19)99812-5598', 'joaopedrosantos@email.com'),
('25678941300', 'Ana Clara Souza', '(19)99567-3344', 'anaclara.souza@gmail.com');


INSERT INTO FUNCIONARIO (FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES
("9876543210", "José Vanderlei", "1985-03-12", "11987654321", "ze_vanderlei@gmail.com", "carteira_vanderlei.pdf", "1234", "56789", "2020-01-15", "44 horas", "12335678000101"),
("1234567890", "Maria Eduarda Lima", "1992-07-25", "11991234567", "mariaeduarda.lima@gmail.com", "carteira_maria.pdf", "2345", "67890", "2019-05-10", "40 horas", "27894563000155"),
("2345678901", "Rafael Nogueira", "1988-11-02", "11999887766", "rafaelnogueira@email.com", "carteira_rafael.pdf", "3456", "78901", "2021-03-22", "44 horas", "56433219000189"),
("3456789012", "Beatriz Fernandes", "1995-09-18", "11988776655", "bia.fernandes@gmail.com", "carteira_beatriz.pdf", "4567", "89012", "2022-07-30", "36 horas", "89745632000102"),
("4567890123", "Carlos Henrique Souza", "1980-12-05", "11977665544", "carloshsouza@gmail.com", "carteira_carlos.pdf", "5678", "90123", "2018-10-12", "40 horas", "33428977000144");


INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES
('12335678000101', 1),
('12335678000101', 2),
('27894563000155', 3),
('27894563000155', 4),
('56433219000189', 5);


INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES
('41531446817', 1),
('41531446817', 3),
('52987412390', 2),
('38421657902', 4),
('71894563211', 5);


SELECT * FROM SUPERMERCADO;

-- ALTERAÇÃO SIMPLES
/*CONSULTAR O AUMENTO DE R$ 2,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL >= R$ 5,00*/
SELECT  PRO_NOME AS "NOME", 
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO + 2),2) AS "PREÇO COM AJUSTE DE R$ 2,00"
FROM 	PRODUTO
WHERE	PRO_PRECO >= 5;

/* CONSULTAR A REDUÇÃO DE R$ 1,00 NO PREÇO DOS PRODUTOS 
COM PREÇO ATUAL ABAIXO DE R$ 5,00*/
SELECT	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO ATUAL",
        TRUNCATE((PRO_PRECO - 1), 2) AS "PREÇO COM REDUÇÃO DE R$ 1,00"
FROM 	PRODUTO
WHERE	PRO_PRECO <= 10;

/*
CONSULTAR COMO SERIA APLICAR UM DESCONTO DE 10% EM TODOS OS PRODUTOS
*/
SELECT	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PRECO ATUAL",
        TRUNCATE((PRO_PRECO - (PRO_PRECO * 0.1)),2) AS "PREÇO COM DESCONTO DE 10%"
FROM PRODUTO;

/* AJUSTAR O ESTOQUE DO PRIMEIRO PRODUTO, DIVIDINDO PELA METADE*/
SELECT 	PRO_NOME, PRO_CODIGO_BARRAS, PRO_QUANTIDADE
FROM	PRODUTO;

UPDATE	PRODUTO
SET		PRO_QUANTIDADE = PRO_QUANTIDADE/2
WHERE	PRO_ID = 1;


/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM DATA DE VALIDADE ENTRE 
SETEMBRO DE 2025 E DEZEMBRO DE 2025*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_DATA_VALIDADE AS "DATA DE VALIDADE"
FROM 	PRODUTO
WHERE	PRO_DATA_VALIDADE BETWEEN '2025-09-01' AND '2025-12-31';


/*CONSULTAR TODOS OS PRODUTOS QUE TENHAM 
PREÇO MAIOR QUE R$ 10 OU MENOR QUE R$ 4*/
SELECT 	PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        PRO_PRECO AS "PREÇO"
FROM	PRODUTO
WHERE	PRO_PRECO >= 10 OR PRO_PRECO <= 4;


/*CONSULTAR OS DDS E TELEFONE DOS CONSUMIDORES SEPARADAMENTE*/
SELECT 	CON_NOME 	AS "NOME DO CONSUMIDOR",
		CON_CPF  	AS "CPF DO CONSUMIRDOR",
        SUBSTRING(CON_TELEFONE,2,2) AS "DDD DO TELEFONE",
        SUBSTRING(CON_TELEFONE,5,10) AS "NÚMERO DO TELEFONE"
FROM	CONSUIMIDOR;


/*GERAR UMA FRASE CONCATENANDO (JUNTANDO):
RAZÃO SOCIAL, CNPJ, TELEFONE E EMAIL*/
SELECT	CONCAT("Razão Social: ", 
			CONCAT(SUP_RAZAO_SOCIAL,
				CONCAT(" | CNPJ: ",
					CONCAT(SUP_CNPJ,
						CONCAT(" | Telefone: ",
							CONCAT(SUP_TELEFONE,
								CONCAT(" | Email: ", SUP_EMAIL))))))) AS FRASE
FROM	SUPERMERCADO;


/*GERAR UMA CONSULTA QUE VERIFICA O STATUS DO ESTOQUE DOS PRODUTOS.
REGRAS:
1) QUANTIDADE <= 25: ESTOQUE BAIXO
2) QUANTIDADE > 25 E QUANTIDADE <= 100: ESTOQUE MÉDIO
3) QUANTIDADE > 100: ESTOQUE ALTO*/
SELECT	PRO_NOME 			AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS 	AS "CÓDIGO DE BARRAS",
        PRO_QUANTIDADE		AS "QUANTIDADE",
        CASE
			WHEN PRO_QUANTIDADE <= 25 THEN "ESTOQUE BAIXO"
            WHEN PRO_QUANTIDADE > 25 AND PRO_QUANTIDADE < 100 THEN "ESTOQUE MÉDIO"
            WHEN PRO_QUANTIDADE >= 100 THEN "ESTOQUE ALTO"
		END AS "NÍVEL DE ESTOQUE"
FROM	PRODUTO;

/*GERAR UMA CONSULTA QUE VERIFICA O PESO DOS PRODUTOS.
RETORNAR: NOME, CÓDIGO DE BARRAS, QUANTIDADE, PESO E DATA DE VALIDADE
REGRAS:
1) PESO <= 5: PESO BAIXO
2) PESO > 5 E PESO <= 50: PESO MÉDIO
3) PESO > 50: PESO ALTO*/
SELECT	PRO_NOME 			AS "NOME DO PRODUTO",
		PRO_CODIGO_BARRAS 	AS "CÓDIGO DE BARRAS",
        PRO_QUANTIDADE		AS "QUANTIDADE",
        PRO_PESO 			AS "PESO",
        PRO_DATA_VALIDADE	AS "DATA DE VALIDADE",
        CASE
			WHEN PRO_PESO <= 5 THEN "PESO BAIXO"
            WHEN PRO_PESO > 5 AND PRO_PESO <= 50 THEN "PESO MÉDIO"
            WHEN PRO_PESO > 50 THEN "PESO ALTO"
		END AS "NÍVEL DE PESO"
FROM	PRODUTO;


/*CONTAR QUANTOS CONSUMIDORES TEMOS CADASTRADOS*/
SELECT 	COUNT(*)
FROM 	CONSUIMIDOR;
/*CONTAR QUANTOS SUPERMERCADOS TEMOS CADASTRADOS*/
SELECT	COUNT(*)
FROM	SUPERMERCADO;
/*CONTAR QUANTOS FUNCIONARIOS TEMOS CADASTRADOS*/
SELECT 	COUNT(*)
FROM 	FUNCIONARIO;
/*CONTAR QUANTOS PRODUTOS TEMOS CADASTRADOS*/
SELECT 	COUNT(*)
FROM 	PRODUTO;


/*SOMAR O PRECO TOTAL DE TODOS OS PRODUTOS CADASTRADOS*/
SELECT 	SUM(PRO_PRECO)
FROM 	PRODUTO;

SELECT 	CONCAT("R$ ", TRUNCATE(SUM(PRO_PRECO),2)) AS "SOMA TOTAL"
FROM 	PRODUTO;


/*CALCULAR A MÉDIA DE PREÇOS DOS PRODUTOS*/
SELECT	AVG(PRO_PRECO)
FROM	PRODUTO;

SELECT	CONCAT("R$ ", TRUNCATE(AVG(PRO_PRECO),2)) AS "MÉDIA DE PREÇO"
FROM	PRODUTO;


/*SELECIONAR O PRODUTO MAIS CARO*/
SELECT	MAX(PRO_PRECO)
FROM	PRODUTO;
/*SELECIONAR ESTOQUE COM MAIOR QUANTIDADE*/
SELECT	MAX(PRO_QUANTIDADE)
FROM	PRODUTO;

/*SELECIONAR O PRODUTO MAIS BARATO*/
SELECT	MIN(PRO_PRECO)
FROM 	PRODUTO;
/*SELECIONAR O ESTOQUE COM MENOR QUANTIDADE*/
SELECT	MIN(PRO_QUANTIDADE)
FROM	PRODUTO;


/*SELECIONAR A DATA E HORA ATUAL*/
SELECT	NOW() FROM DUAL;

SELECT 	FUN_NOME AS "NOME DO FUNCIONÁRIO",
		DATE_FORMAT(FUN_DATA_NASCIMENTO, "%d/%m/%Y") AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF(YEAR,FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM	FUNCIONARIO;


/*FUNÇÕES MATEMÁTICAS:
ABS - VALOR ABSOLUTO DE UM NÚMERO
ROUND - ARRREDONDAR
POWER - POTÊNCIA*/
SELECT 	ABS(-10),
		ROUND(PRO_PRECO) AS "PREÇO ARREDONDADO",
        POWER(PRO_PRECO,2) AS "PREÇOS ELEVADOS AO QUADRADO"
FROM	PRODUTO;


/*UPPER, LOWER, TRIM*/
SELECT 	UPPER(FUN_NOME) AS "MAIÚSCULAS",
		LOWER(FUN_NOME) AS "MINÚSCULAS",
        TRIM("        Thaiene") AS "TIRANDO ESPAÇOS"
FROM	FUNCIONARIO;




/*AGRUPAMENTO DE DADOS*/
/*Agrupar produtos com a mesma quantidade de estoque*/
SELECT 	PRO_QUANTIDADE,
		COUNT(*) AS "REPETIÇÕES"
FROM	PRODUTO
GROUP BY PRO_QUANTIDADE;



/*UNION*/
SELECT	FUN_NOME,
		FUN_CPF
FROM	FUNCIONARIO
UNION
SELECT	FUN_NOME,
		FUN_CPF
FROM	FUNCIONARIO;

SELECT * FROM 	PRODUTO;

/*UNION*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION
SELECT	"Arroz 5kg"
FROM	DUAL
UNION
SELECT	"Iogurt do Bob Esponja"
FROM	DUAL;

/*UNION ALL*/
SELECT	PRO_NOME
FROM	PRODUTO
UNION ALL
SELECT	"Arroz 5kg"
FROM	DUAL
UNION ALL
SELECT	"Iogurt do Bob Esponja"
FROM	DUAL;
	
/*SELECT COM WHERE*/
SELECT	FUN_NOME			AS "NOME DO FUNCIONÁRIO",
		FUN_CPF				AS "CPF DO FUNCIONÁRIO",
        FUN_DATA_NASCIMENTO AS "DATA DE NASCIMENTO",
        TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO, NOW()) AS "IDADE"
FROM	FUNCIONARIO
WHERE	TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO, NOW()) >= 25
AND		TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO, NOW()) <= 35;

/*RETORNAR OS FUNCIONÁRIOS, CONSUMIDORES E SUPERMERCADOS
COM EMAIL IGUAL A HOTMAIL OU OUTLOOK*/
SELECT	CON_NOME			AS "NOME",
		CON_CPF				AS "CPF/CNPJ",
        CON_TELEFONE		AS "TELEFONE",
        CON_EMAIL			AS "EMAIL",
        "CONSUMIDOR"		AS "TIPO"
FROM	CONSUIMIDOR
WHERE	UPPER(CON_EMAIL)	LIKE "%EMAIL%"
OR 		UPPER(CON_EMAIL)	LIKE "%OUTLOOK%"

UNION
SELECT	FUN_NOME			AS "NOME",
		FUN_CPF				AS "CPF/CNPJ",
        FUN_TELEFONE		AS "TELEFONE",
        FUN_EMAIL			AS "EMAIL",
        "FUNCIONARIO"		AS "TIPO"
FROM	FUNCIONARIO
WHERE	UPPER(FUN_EMAIL)	LIKE "%EMAIL%"
OR 	 	UPPER(FUN_EMAIL)	LIKE "%OUTLOOK%"

UNION
SELECT	SUP_RAZAO_SOCIAL	AS "NOME",
		SUP_CNPJ			AS "CPF/CNPJ",
        SUP_TELEFONE		AS "TELEFONE",
        SUP_EMAIL			AS "EMAIL",
        "SUPERMERCADO"		AS "TIPO"
FROM	SUPERMERCADO
WHERE	UPPER(SUP_EMAIL)	LIKE "%EMAIL%"
OR 	 	UPPER(SUP_EMAIL)	LIKE "%OUTLOOK%";



/*CROSS JOIN:
RETORNAR TODOS OS PRODUTOS E OS SUPERMERCADOS EM QUE SÃO VENDIDOS*/
SELECT		PRODUTO.PRO_NOME				AS "NOME",
			PRODUTO.PRO_CODIGO_BARRAS 		AS "CÓDIGO DE BARRAS",
			SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "RAZÃO SOCIAL"
FROM 		SUPERMERCADO_PRODUTO
CROSS JOIN	SUPERMERCADO
CROSS JOIN 	PRODUTO
WHERE		PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID
AND			SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ;


/*INNER JOIN
RETORNAR APENAS OS PRODUTOS QUE FORAM COMPRADOS POR ALGUM CONSUMIDOR*/
SELECT		PRODUTO_CONSUMIDOR.PCD_ID	AS "ID DA COMPRA",
			PRODUTO.PRO_NOME			AS "NOME DO PRODUTO",
            PRODUTO.PRO_CODIGO_BARRAS	AS "CÓDIGO DE BARRAS",
            CONSUIMIDOR.CON_NOME		AS "NOME DO CONSUMIDOR",
            CONSUIMIDOR.CON_CPF			AS "CPF DO CONSUMIDOR"
FROM 		PRODUTO_CONSUMIDOR
INNER JOIN	PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN	CONSUIMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUIMIDOR.CON_CPF);


/*EXERCÍCIO COM INNNER JOIN
RETORNAR APENAS OS FUNCIONARIOS QUE TRABALHAM EM UM SUPERMERCADO
RETORNAR O NOME DO FUNCIONÁRIO E O NOME DO SUPERMERCADO QUE ELE TRABALHA*/
SELECT		SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "RAZÃO SOCIAL",
			FUNCIONARIO.FUN_NOME			AS "NOME DO FUNCIONÁRIO"
FROM 		SUPERMERCADO
INNER JOIN	FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);


/*EXERCÍCIO 2 COM INNER JOIN
RETORNAR APENAS OS PRODUTOS QUE EXISTAM EM UM SUPERMERCADO
RETORNAR O NOME DO PRODUTO E O NOME DO SUPERMERCADO QUE ELE ESTÁ DISPONÍVEL*/
SELECT		PRODUTO.PRO_NOME				AS "NOME DO PRODUTO",
			SUPERMERCADO.SUP_RAZAO_SOCIAL	AS "NOME DO SUPERMERCADO"
FROM		SUPERMERCADO_PRODUTO
INNER JOIN	SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN	PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);


/*LEFT JOIN*/
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES				("33333333", "KitKat", "30", "1500", 4.50, "2026-01-01");

SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM 	PRODUTO
LEFT JOIN 	SUPERMERCADO_PRODUTO	ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
LEFT JOIN 	SUPERMERCADO 			ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);


/*RIGHT JOIN*/
SELECT * FROM SUPERMERCADO; 

SELECT	PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM 	PRODUTO
RIGHT JOIN 	SUPERMERCADO_PRODUTO	ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
RIGHT JOIN 	SUPERMERCADO 			ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);


/*SELECT COM LEFT JOIN E RIGHT JOIN*/
SELECT 	*
FROM 	(
			SELECT 		S.SUP_RAZAO_SOCIAL 	AS RAZAO_SOCIAL,
						F.FUN_NOME 			AS NOME_FUNCIONARIO,
						P.PRO_NOME 			AS NOME_PRODUTO,
						C.CON_NOME 			AS NOME_CONSUMIDOR
			FROM SUPERMERCADO S 
            LEFT JOIN 	FUNCIONARIO F 			ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
            LEFT JOIN	SUPERMERCADO_PRODUTO SP	ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
            LEFT JOIN	PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
            LEFT JOIN 	PRODUTO_CONSUMIDOR PC 	ON (P.PRO_ID = PC.FK_PRO_ID)
            LEFT JOIN 	CONSUIMIDOR C 			ON (PC.FK_CON_CPF = C.CON_CPF)
            
            UNION
            SELECT 		S.SUP_RAZAO_SOCIAL 	AS RAZAO_SOCIAL,
						F.FUN_NOME 			AS NOME_FUNCIONARIO,
						P.PRO_NOME 			AS NOME_PRODUTO,
						C.CON_NOME 			AS NOME_CONSUMIDOR
			FROM SUPERMERCADO S 
            RIGHT JOIN 	FUNCIONARIO F 			ON (S.SUP_CNPJ = F.FK_SUP_CNPJ)
            RIGHT JOIN	SUPERMERCADO_PRODUTO SP ON (S.SUP_CNPJ = SP.FK_SUP_CNPJ)
            RIGHT JOIN	PRODUTO P 				ON (SP.FK_PRO_ID = P.PRO_ID)
            RIGHT JOIN 	PRODUTO_CONSUMIDOR PC 	ON (P.PRO_ID = PC.FK_PRO_ID)
            RIGHT JOIN 	CONSUIMIDOR C 			ON (PC.FK_CON_CPF = C.CON_CPF)
) SELECT_EXTERNO
ORDER BY 	SELECT_EXTERNO.RAZAO_SOCIAL 	ASC,
			SELECT_EXTERNO.NOME_FUNCIONARIO DESC,
            SELECT_EXTERNO.NOME_PRODUTO 	ASC,
            SELECT_EXTERNO.NOME_CONSUMIDOR 	DESC;
            
            
/* ASSOCIAÇÃO DE TABELAS - EXERCÍCIO 1 - INNER JOIN*/
SELECT		PRODUTO.PRO_NOME				AS "NOME DO PRODUTO",
			SUPERMERCADO.SUP_RAZAO_SOCIAL	AS "NOME DO SUPERMERCADO"
FROM		SUPERMERCADO_PRODUTO
INNER JOIN	SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN	PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/* EXERCÍCIO 2 - INNER JOIN*/
SELECT		SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "SUPERMERCADO",
			FUNCIONARIO.FUN_NOME			AS "NOME DO FUNCIONÁRIO"
FROM 		SUPERMERCADO
INNER JOIN	FUNCIONARIO ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/* EXERCÍCIO 3 - INNER JOIN*/
SELECT 		CONSUIMIDOR.CON_NOME			AS "NOME DO CONSUMIDOR",
			PRODUTO.PRO_NOME 				AS "PRODUTO"
FROM 		PRODUTO_CONSUMIDOR
INNER JOIN	PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID)
INNER JOIN	CONSUIMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUIMIDOR.CON_CPF);

/* EXERCÍCIO 4 - INNER JOIN*/	
SELECT 		PRODUTO.PRO_NOME 				AS "PRODUTO",
			CONSUIMIDOR.CON_NOME			AS "NOME DO CONSUMIDOR"
FROM 		PRODUTO_CONSUMIDOR
INNER JOIN	CONSUIMIDOR ON (PRODUTO_CONSUMIDOR.FK_CON_CPF = CONSUIMIDOR.CON_CPF)
INNER JOIN	PRODUTO ON (PRODUTO_CONSUMIDOR.FK_PRO_ID = PRODUTO.PRO_ID);

/* EXERCÍCIO 5 - INNER JOIN*/
SELECT		SUPERMERCADO.SUP_RAZAO_SOCIAL AS "SUPERMERCADO",
			COUNT(*) AS "QUANTIDADE DE PRODUTOS"
FROM		SUPERMERCADO_PRODUTO
INNER JOIN	SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN	PRODUTO ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID)
GROUP BY 	SUPERMERCADO.SUP_RAZAO_SOCIAL;

/* EXERCÍCIO 1 - LEFT JOIN*/
SELECT		SUPERMERCADO.SUP_RAZAO_SOCIAL,
			PRODUTO.PRO_NOME
FROM		SUPERMERCADO
LEFT JOIN	SUPERMERCADO_PRODUTO	ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
LEFT JOIN 	PRODUTO 				ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/* EXERCÍCIO 2 - LEFT JOIN*/
SELECT		FUNCIONARIO.FUN_NOME,
			SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM		FUNCIONARIO
LEFT JOIN 	SUPERMERCADO 			ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/* EXERCÍCIO 3 - LEFT JOIN*/
SELECT 		CONSUIMIDOR.CON_NOME,
			PRODUTO.PRO_NOME
FROM 		CONSUIMIDOR
LEFT JOIN 	PRODUTO_CONSUMIDOR 		ON (CONSUIMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF)
LEFT JOIN	PRODUTO 				ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID);

/* EXERCÍCIO 4 - LEFT JOIN*/
SELECT		PRODUTO.PRO_NOME, 		
			CONSUIMIDOR.CON_NOME
FROM 		PRODUTO
LEFT JOIN 	PRODUTO_CONSUMIDOR 		ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID)
LEFT JOIN	CONSUIMIDOR 			ON (CONSUIMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF);

/* EXERCÍCIO 5 - LEFT JOIN*/
SELECT		SUPERMERCADO.SUP_RAZAO_SOCIAL,
			FUNCIONARIO.FUN_NOME
FROM		SUPERMERCADO
LEFT JOIN 	FUNCIONARIO 			ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCÍCIO 1 - RIGHT JOIN*/
SELECT 		SUPERMERCADO.SUP_RAZAO_SOCIAL,
			PRODUTO.PRO_NOME
FROM		SUPERMERCADO
RIGHT JOIN	SUPERMERCADO_PRODUTO 	ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
RIGHT JOIN 	PRODUTO 				ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*EXERCÍCIO 2 - RIGHT JOIN*/
SELECT		CONSUIMIDOR.CON_NOME,
			PRODUTO.PRO_NOME		
FROM 		CONSUIMIDOR
RIGHT JOIN 	PRODUTO_CONSUMIDOR 		ON (CONSUIMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF)
RIGHT JOIN	PRODUTO 	 			ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID);

/*EXERCÍCIO 3 - RIGHT JOIN*/
SELECT 		FUNCIONARIO.FUN_NOME,
			SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM        FUNCIONARIO
RIGHT JOIN 	SUPERMERCADO 			ON (SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCÍCIO 4 - RIGHT JOIN*/
SELECT 		SUPERMERCADO.SUP_RAZAO_SOCIAL,
			PRODUTO.PRO_NOME
FROM		SUPERMERCADO
RIGHT JOIN	SUPERMERCADO_PRODUTO 	ON (SUPERMERCADO.SUP_CNPJ = SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
RIGHT JOIN 	PRODUTO 				ON (PRODUTO.PRO_ID = SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*EXERCÍCIO 5 - RIGHT JOIN*/
SELECT		CONSUIMIDOR.CON_NOME,
			PRODUTO.PRO_NOME		
FROM 		CONSUIMIDOR
RIGHT JOIN 	PRODUTO_CONSUMIDOR 		ON (CONSUIMIDOR.CON_CPF = PRODUTO_CONSUMIDOR.FK_CON_CPF)
RIGHT JOIN	PRODUTO 	 			ON (PRODUTO.PRO_ID = PRODUTO_CONSUMIDOR.FK_PRO_ID);





/*SUBCONSULTAS - IN*/
/* Selecionar apenas os PRODUTOS que possuem registro
em um SUPERMERCADO e que forsm comprados por um CONSUMIDOR*/
SELECT 	P.PRO_NOME 			AS "NOME DO PRODUTO",
		P.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        P.PRO_PRECO 		AS "PREÇO DO PRODUTO"
FROM 	PRODUTO P 
WHERE 	P.PRO_ID IN (SELECT SP.FK_PRO_ID FROM SUPERMERCADO_PRODUTO SP)
AND 	P.PRO_ID IN (SELECT PC.FK_PRO_ID FROM PRODUTO_CONSUMIDOR PC);

/*SUBCONSULTAS - NOT IN*/
/*Selecionar apenas os PRODUTOS que NÃO possuem registro
em um SUPERMERCADO e que NÃO foram comprados por um CONSUMIDOR*/
SELECT 	P.PRO_NOME 			AS "NOME DO PRODUTO",
		P.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        P.PRO_PRECO 		AS "PREÇO DO PRODUTO"
FROM 	PRODUTO P 
WHERE 	P.PRO_ID NOT IN (SELECT SP.FK_PRO_ID FROM SUPERMERCADO_PRODUTO SP)
AND 	P.PRO_ID NOT IN (SELECT PC.FK_PRO_ID FROM PRODUTO_CONSUMIDOR PC);

/*SUBCONSULTAS - ALL*/
/*Selecionar os SUPERMERCADOS que tem o preço de todos os produtos
menor que 10*/
SELECT 	S.SUP_RAZAO_SOCIAL
FROM 	SUPERMERCADO S 
WHERE 	10 > ALL (
		SELECT 	P.PRO_PRECO
        FROM 	PRODUTO P
);

/*SUBCONSULTAS - ANY*/
/* Listar todos os PRODUTOS cujo preço seja maior que o preço de 
qualquer PRODUTO vendido no SUPERMERCADO com CNPJ 12345658000101*/
SELECT 	PRO_NOME,
		PRO_PRECO
FROM 	PRODUTO 
WHERE 	PRO_PRECO > ANY (
	SELECT 		P.PRO_PRECO
    FROM 		PRODUTO P
    INNER JOIN 	SUPERMERCADO_PRODUTO SP
    ON 			(P.PRO_ID = SP.FK_PRO_ID)
    WHERE 		SP.FK_SUP_CNPJ = '12345678000101'
);


/*SUBCONSULTAS - EXISTS*/
/*Listar todos os consumidores que compraram pelo menos UM produto*/
SELECT 	C.CON_NOME,
		C.CON_CPF
FROM 	CONSUIMIDOR C 
WHERE 	EXISTS (
	SELECT 	1
    FROM 	PRODUTO_CONSUMIDOR PC
    WHERE 	PC.FK_CON_CPF = C.CON_CPF
);


/*SUBCONSULTAS - NOT EXISTS*/
/*Listar todos os consumidores que  NÃO compraram NENHUM produto*/
SELECT 	C.CON_NOME,
		C.CON_CPF
FROM 	CONSUIMIDOR C 
WHERE 	NOT EXISTS (
	SELECT 	1
    FROM 	PRODUTO_CONSUMIDOR PC
    WHERE 	PC.FK_CON_CPF = C.CON_CPF
);


/* TCL - LINGUAGEM DE CONTROLE DE TRANSAÇÕES: COMMIT*/
-- PASSO 1: INICIAR A TRANSAÇÃO 
START TRANSACTION; 

-- PASSO 2: ESCREVER O COMANDO DML
INSERT INTO SUPERMERCADO 	(SUP_CNPJ,
							SUP_RAZAO_SOCIAL,
                            SUP_TELEFONE,
                            SUP_EMAIL,
                            SUP_ENDERECO_LOGRADOURO,
                            SUP_ENDERECO_NUMERO,
                            SUP_ENDERECO_CIDADE,
                            SUP_ENDERECO_ESTADO)
VALUES 						('11111111000111',
							'Supermercado Pontes',
                            '11987654321',
                            'pontes@pontes.com',
                            'Rua do Pontes',
                            '100',
                            'Tambaú',
                            'SP');
                            
-- PASSO 3: SE TUDO DEU CERTO, ENVIA PRO BANCO
COMMIT;


/* TCL: ROLLBACK*/
-- PASSO 1: INICIAR A TRANSAÇÃO 
START TRANSACTION; 

-- PASSO 2: ESCREVER O COMANDO DML
INSERT INTO SUPERMERCADO 	(SUP_CNPJ,
							SUP_RAZAO_SOCIAL,
                            SUP_TELEFONE,
                            SUP_EMAIL,
                            SUP_ENDERECO_LOGRADOURO,
                            SUP_ENDERECO_NUMERO,
                            SUP_ENDERECO_CIDADE,
                            SUP_ENDERECO_ESTADO)
VALUES 						('11111111000111',
							'Supermercado Pontes',
                            '11987654321',
                            'pontes@pontes.com',
                            'Rua do Pontes',
                            '100',
                            'Tambaú',
                            'SP');
                            
-- PASSO 3: SE TUDO DEU CERTO, ENVIA PRO BANCO
ROLLBACK;




/* TCL: SAVEPOINT*/
START TRANSACTION;

-- Inserir um novo supermercado
INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL,
SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES 	('333333330033', 'Supermercado Nova Era', '11987654321', 'contato@novaera.com.br',
'Rua Nova', '150', 'Porto-Alegre','RS');

-- Criar um ponto de salvamento (savepoint)
SAVEPOINT savepoint_produto1;

-- Inserir o primeiro produto
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("12345678987", "Açúcar 1kg", 1.0, 200, 3.00, "2025-06-30");

-- Criar um segundo ponto de salvamento (savepoint)
SAVEPOINT savepoint_produto2;

-- Inserir o segundo produto com um dado inválido (simulação de erro)
INSERT INTO PRODUTO (PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("9876543210123", "Café 500g",'500g', -100, 15.00, "2025-09-30"); -- Quantidade negativa (erro)

-- Se ocorrer um erro, reverter apenas até o segundo savepoint
ROLLBACK TO savepoint_produto2;

-- Confirmar as mudanças até o primeiro savepoint
COMMIT;